board:
    gameIsActive: true
    rows: 3
    columns: 3
    cells: [[{ content: 0, rating: 3 }, { content: 0, rating: 2 }, { content: 0, rating: 2 }, { content: 0, rating: 3 }], [{ content: 0, rating: 2 }, { content: 0, rating: 3 }, { content: 0, rating: 3 }, { content: 0, rating: 2 }], [{ content: 0, rating: 2 }, { content: 0, rating: 3 }, { content: 0, rating: 3 }, { content: 0, rating: 2 }], [{ content: 0, rating: 3 }, { content: 0, rating: 2 }, { content: 0, rating: 2 }, { content: 0, rating: 3 }]]
    turn: Human
